### ISSUE TITLE
CSS not loaded in the correct order

### ISSUE THREAD

**Issue by jgrenat** [geelen/jspm-loader-css#9]
Hi,

Yesterday, I tried to import some CSS files. In two of these files, I have rules with the same priority, something like : 

``` css
/* File 1 */
.my-class {
    background-color: red;
}

/* File 2 */
.my-class {
    background-color: green;
}
```

``` js
import 'file1.css';
import 'file2.css';
```

The expected result is to have a green background, but as my first file is heavier than my first, it's loaded after the second one, making my override fail.
